const serviceCopy = {
    en: {},
    fr: {
        "Annual PR Plan": { title: "Plan annuel de relations publiques", description: "Élaboration du plan annuel de relations publiques." },
        "Situation Analysis": { title: "Analyse de la situation", description: "Analyse approfondie de la position actuelle de l'institution." },
        "Target Audience Identification": { title: "Identification du public cible", description: "Identification et profilage du public cible." },
        "Key Messaging": { title: "Messages clés", description: "Construction des messages de communication principaux." },
        "Roadmap Development": { title: "Feuille de route", description: "Élaboration d'une feuille de route exécutive pour les RP." },
        "KPI Setting": { title: "Définition des KPI", description: "Définition des indicateurs de performance pour les campagnes RP." },
        "Audience Research": { title: "Étude du public", description: "Étude approfondie pour comprendre le public cible." },
        "Competitor Analysis PR": { title: "Analyse concurrentielle RP", description: "Analyse des concurrents du point de vue des RP." },
        "Audience Segmentation": { title: "Segmentation du public", description: "Segmentation du public en groupes exploitables." },
        "Communication Channels": { title: "Canaux de communication", description: "Identification des canaux de communication les plus efficaces." },
        "Analytical Reports": { title: "Rapports analytiques", description: "Préparation de rapports analytiques détaillés." },
        "Institution Image Analysis": { title: "Analyse d'image", description: "Analyse de l'image publique de l'institution." },
        "Online Monitoring": { title: "Veille en ligne", description: "Surveillance de ce qui se dit sur l'institution en ligne." },
        "Media Coverage Measurement": { title: "Mesure de couverture médiatique", description: "Mesure du volume et de la qualité de la couverture médiatique." },
        "Competitor Benchmarking": { title: "Benchmarking concurrentiel", description: "Comparaison de la réputation avec les concurrents." },
        "Reputation Reports": { title: "Rapports de réputation", description: "Rapports de réputation et recommandations." },
        "Image Improvement": { title: "Amélioration de l'image", description: "Amélioration de l'image publique globale." },
        "Positive Content Creation": { title: "Création de contenu positif", description: "Création de contenu positif pour renforcer la réputation." },
        "Influencer Collaboration": { title: "Collaboration avec des influenceurs", description: "Collaboration avec des influenceurs pour la confiance." },
        "Community Management": { title: "Gestion de communauté", description: "Gestion des comptes et réponses aux commentaires." },
        "Continuous Monitoring": { title: "Surveillance continue", description: "Surveillance continue de la réputation et du sentiment." },
        "Proactive Crisis Plan": { title: "Plan de crise proactif", description: "Élaboration d'un plan proactif de gestion de crise." },
        "Risk Analysis": { title: "Analyse des risques", description: "Identification et évaluation des risques potentiels." },
        "Crisis Scenarios": { title: "Scénarios de crise", description: "Préparation de scénarios pour diverses crises." },
        "Team Training": { title: "Formation de l'équipe", description: "Formation de l'équipe pour réagir efficacement aux crises." },
        "Immediate Crisis Intervention": { title: "Intervention immédiate", description: "Réponse immédiate au début d'une crise." },
        "Professional Crisis Decisions": { title: "Décisions professionnelles", description: "Prise de décision experte pendant une crise." },
        "Real-Time Follow-Up": { title: "Suivi en temps réel", description: "Surveillance et réponse en temps réel pendant la crise." },
        "Official Media Statements": { title: "Déclarations officielles", description: "Rédaction et diffusion de réponses médiatiques officielles." },
        "Continuous Crisis Support": { title: "Support continu", description: "Support continu pendant toute la période de crise." },
        "Trust Restoration": { title: "Restauration de la confiance", description: "Restauration de la confiance publique après une crise." },
        "Post-Crisis Image Improvement": { title: "Amélioration post-crise", description: "Amélioration de l'image après une crise." },
        "Damage Assessment": { title: "Évaluation des dommages", description: "Évaluation de l'impact et des dommages causés par la crise." },
        "Performance Improvement": { title: "Amélioration des performances", description: "Amélioration basée sur les leçons post-crise." },
        "Press Releases": { title: "Communiqués de presse", description: "Rédaction de communiqués de presse professionnels." },
        "Article Writing": { title: "Rédaction d'articles", description: "Rédaction d'articles pour les médias et publications." },
        "Digital Content": { title: "Contenu numérique", description: "Préparation de contenu numérique pour les plateformes." },
        "Communication Scripts": { title: "Scripts de communication", description: "Rédaction de scripts de communication et messagerie." },
        "Multilingual Content": { title: "Contenu multilingue", description: "Création de contenu en plusieurs langues." },
        "Media Network Building": { title: "Réseau médiatique", description: "Construction d'un réseau de contacts médiatiques." },
        "Press Release Distribution": { title: "Diffusion de communiqués", description: "Diffusion de communiqués de presse aux médias." },
        "Coverage Follow-Up": { title: "Suivi de couverture", description: "Suivi et surveillance de la couverture médiatique." },
        "Press Conferences": { title: "Conférences de presse", description: "Organisation de conférences de presse." },
        "Visual Design": { title: "Design visuel", description: "Conception de contenu visuel professionnel." },
        "Professional Posts": { title: "Publications professionnelles", description: "Création de publications soignées pour les réseaux sociaux." },
        "Short Videos": { title: "Vidéos courtes", description: "Production de vidéos promotionnelles courtes." },
        "Motion Graphics": { title: "Motion Graphics", description: "Conception de motion graphics pour les plateformes numériques." },
        "Digital Presence Analysis": { title: "Analyse de présence numérique", description: "Analyse complète de la présence numérique." },
        "General Sentiment Measurement": { title: "Mesure du sentiment", description: "Mesure du sentiment numérique global du public." },
        "Comments Analysis": { title: "Analyse des commentaires", description: "Analyse des commentaires et réactions en ligne." },
        "Digital Competitor Benchmarking": { title: "Benchmarking numérique", description: "Comparaison de la réputation numérique avec les concurrents." },
        "Digital Presence Improvement": { title: "Amélioration de la présence", description: "Amélioration de l'empreinte numérique de l'institution." },
        "Engagement Management": { title: "Gestion de l'engagement", description: "Gestion et croissance de l'interaction en ligne." },
        "Professional Content Publishing": { title: "Publication de contenu pro", description: "Publication de contenu professionnel sur les canaux." },
        "Performance Tracking": { title: "Suivi de performance", description: "Surveillance et reporting de la performance numérique." },
        "Ads Management": { title: "Gestion publicitaire", description: "Gestion des campagnes publicitaires numériques." },
        "SEO Optimization": { title: "Optimisation SEO", description: "Optimisation du référencement naturel." },
        "Email Marketing": { title: "Email marketing", description: "Campagnes d'email marketing stratégiques." },
        "Content Marketing": { title: "Marketing de contenu", description: "Création et diffusion de contenus marketing." },
        "Market Study": { title: "Étude de marché", description: "Recherches et études de marché complètes." },
        "Competitor Analysis Mkt": { title: "Analyse concurrentielle", description: "Analyse approfondie des concurrents." },
        "Target Audience Definition": { title: "Définition de l'audience", description: "Identification et profilage des audiences cibles." },
        "Brand Building": { title: "Construction de marque", description: "Développement stratégique de la présence de marque." },
        "Promotional Campaigns": { title: "Campagnes promotionnelles", description: "Campagnes promotionnelles sur le terrain." },
        "Print Distribution": { title: "Distribution d'imprimés", description: "Distribution de supports promotionnels imprimés." },
        "Events Organization": { title: "Organisation d'événements", description: "Planification et organisation d'événements." },
        "Promoters": { title: "Promoteurs", description: "Recrutement et gestion de promoteurs terrain." },
        "Flyers": { title: "Flyers", description: "Impression de flyers de haute qualité." },
        "Brochures": { title: "Brochures", description: "Impression de brochures personnalisées." },
        "Posters": { title: "Affiches", description: "Impression d'affiches grand format." },
        "Roll-ups": { title: "Roll-ups", description: "Bannières roll-up professionnelles." },
        "Business Cards": { title: "Cartes de visite", description: "Impression de cartes de visite premium." },
        "Administrative Files": { title: "Dossiers administratifs", description: "Dossiers administratifs imprimés." },
        "Official Envelopes": { title: "Enveloppes officielles", description: "Enveloppes de marque professionnelles." },
        "Notebooks": { title: "Carnets", description: "Carnets personnalisés à l'image de la marque." },
        "Visual Identity Design": { title: "Design d'identité visuelle", description: "Pack complet de design d'identité visuelle." },
        "Printing Execution": { title: "Exécution d'impression", description: "Gestion complète de l'exécution d'impression." },
        "Fast Delivery": { title: "Livraison rapide", description: "Services accélérés de design et d'impression." },
        "High Quality Output": { title: "Qualité premium", description: "Sortie de qualité premium pour tous les travaux." },
        "Initial Legal Consultation": { title: "Consultation juridique initiale", description: "Consultation initiale sur les questions juridiques." },
        "Contract Review": { title: "Revue de contrat", description: "Analyse professionnelle des contrats." },
        "Regulatory Advice": { title: "Conseil réglementaire", description: "Conseils réglementaires et de conformité." },
        "Administrative Legal Support": { title: "Support juridique administratif", description: "Accompagnement pour les documents juridiques administratifs." }
    },
    ar: {
        "Annual PR Plan": { title: "خطة العلاقات العامة السنوية", description: "إعداد خطة العلاقات العامة السنوية." },
        "Situation Analysis": { title: "تحليل الوضع الحالي", description: "تحليل معمّق للوضع الحالي للمؤسسة." },
        "Target Audience Identification": { title: "تحديد الجمهور المستهدف", description: "تحديد وتحليل الجمهور المستهدف." },
        "Key Messaging": { title: "بناء الرسائل الرئيسية", description: "بناء الرسائل الأساسية للتواصل المؤسسي." },
        "Roadmap Development": { title: "خارطة طريق تنفيذية", description: "إعداد خارطة طريق تنفيذية لأنشطة العلاقات العامة." },
        "KPI Setting": { title: "تحديد مؤشرات الأداء", description: "تحديد مؤشرات الأداء الرئيسية للحملات." },
        "Audience Research": { title: "دراسة معمقة للجمهور", description: "دراسة معمقة لفهم الجمهور المستهدف." },
        "Competitor Analysis PR": { title: "تحليل المنافسين - علاقات عامة", description: "تحليل المنافسين من منظور العلاقات العامة." },
        "Audience Segmentation": { title: "تقسيم الجمهور", description: "تقسيم الجمهور إلى شرائح قابلة للاستهداف." },
        "Communication Channels": { title: "قنوات التواصل", description: "تحديد أنجع قنوات التواصل." },
        "Analytical Reports": { title: "تقارير تحليلية", description: "إعداد تقارير تحليلية مفصلة." },
        "Institution Image Analysis": { title: "تحليل صورة المؤسسة", description: "تحليل الصورة العامة للمؤسسة." },
        "Online Monitoring": { title: "رصد ما يقال على الإنترنت", description: "مراقبة ما يُقال عن المؤسسة على الإنترنت." },
        "Media Coverage Measurement": { title: "قياس التغطية الإعلامية", description: "قياس حجم وجودة التغطية الإعلامية." },
        "Competitor Benchmarking": { title: "مقارنة مع المنافسين", description: "مقارنة السمعة مع المنافسين." },
        "Reputation Reports": { title: "تقارير وتوصيات", description: "إعداد تقارير السمعة والتوصيات." },
        "Image Improvement": { title: "تحسين صورة المؤسسة", description: "تحسين الصورة العامة للمؤسسة." },
        "Positive Content Creation": { title: "إنشاء محتوى إيجابي", description: "إنشاء محتوى إيجابي لتعزيز السمعة." },
        "Influencer Collaboration": { title: "التعاون مع المؤثرين", description: "التعاون مع المؤثرين لبناء الثقة." },
        "Community Management": { title: "إدارة الحسابات والتعليقات", description: "إدارة الحسابات والرد على التعليقات." },
        "Continuous Monitoring": { title: "متابعة مستمرة", description: "متابعة مستمرة للسمعة والانطباع العام." },
        "Proactive Crisis Plan": { title: "خطة أزمات استباقية", description: "إعداد خطة استباقية لإدارة الأزمات." },
        "Risk Analysis": { title: "تحليل المخاطر", description: "تحديد وتقييم المخاطر المحتملة." },
        "Crisis Scenarios": { title: "سيناريوهات الأزمات", description: "وضع سيناريوهات جاهزة لمختلف الأزمات." },
        "Team Training": { title: "تدريب الفريق", description: "تدريب الفريق على الاستجابة الفعالة للأزمات." },
        "Immediate Crisis Intervention": { title: "تدخل فوري", description: "استجابة فورية عند بداية الأزمة." },
        "Professional Crisis Decisions": { title: "قرارات احترافية", description: "اتخاذ قرارات احترافية أثناء الأزمة." },
        "Real-Time Follow-Up": { title: "متابعة في الوقت الحقيقي", description: "متابعة ورصد في الوقت الحقيقي أثناء الأزمة." },
        "Official Media Statements": { title: "ردود إعلامية رسمية", description: "صياغة وإصدار ردود إعلامية رسمية." },
        "Continuous Crisis Support": { title: "دعم مستمر", description: "دعم مستمر طوال فترة الأزمة." },
        "Trust Restoration": { title: "استعادة الثقة", description: "استعادة ثقة الجمهور بعد الأزمة." },
        "Post-Crisis Image Improvement": { title: "تحسين الصورة بعد الأزمة", description: "تحسين صورة المؤسسة بعد الأزمة." },
        "Damage Assessment": { title: "تقييم الأضرار", description: "تقييم تأثير الأزمة والأضرار الناتجة." },
        "Performance Improvement": { title: "تحسين الأداء", description: "تحسين الأداء بناء على دروس ما بعد الأزمة." },
        "Press Releases": { title: "كتابة بيانات صحفية", description: "كتابة بيانات صحفية احترافية." },
        "Article Writing": { title: "كتابة مقالات", description: "كتابة مقالات للنشر الإعلامي والرقمي." },
        "Digital Content": { title: "إعداد محتوى رقمي", description: "إعداد محتوى رقمي لمختلف المنصات." },
        "Communication Scripts": { title: "نصوص تواصل", description: "كتابة نصوص التواصل والمراسلات." },
        "Multilingual Content": { title: "محتوى متعدد اللغات", description: "إنشاء محتوى بعدة لغات." },
        "Media Network Building": { title: "بناء شبكة علاقات إعلامية", description: "بناء وصيانة شبكة اتصالات إعلامية." },
        "Press Release Distribution": { title: "إرسال البيانات الصحفية", description: "توزيع البيانات الصحفية على وسائل الإعلام." },
        "Coverage Follow-Up": { title: "متابعة التغطيات", description: "متابعة ورصد التغطيات الإعلامية." },
        "Press Conferences": { title: "تنظيم المؤتمرات الصحفية", description: "تنظيم وإدارة المؤتمرات الصحفية." },
        "Visual Design": { title: "تصميم محتوى بصري", description: "تصميم محتوى بصري احترافي." },
        "Professional Posts": { title: "منشورات احترافية", description: "إنشاء منشورات احترافية لوسائل التواصل." },
        "Short Videos": { title: "فيديوهات قصيرة", description: "إنتاج فيديوهات ترويجية قصيرة." },
        "Motion Graphics": { title: "موشن غرافيك", description: "تصميم رسوم متحركة للمنصات الرقمية." },
        "Digital Presence Analysis": { title: "تحليل الحضور الرقمي", description: "تحليل شامل للحضور الرقمي." },
        "General Sentiment Measurement": { title: "قياس الانطباع العام", description: "قياس الانطباع العام الرقمي للجمهور." },
        "Comments Analysis": { title: "تحليل التعليقات", description: "تحليل التعليقات وردود الفعل عبر الإنترنت." },
        "Digital Competitor Benchmarking": { title: "مقارنة المنافسين رقمياً", description: "مقارنة السمعة الرقمية مع المنافسين." },
        "Digital Presence Improvement": { title: "تحسين الوجود الرقمي", description: "تعزيز البصمة الرقمية للمؤسسة." },
        "Engagement Management": { title: "إدارة التفاعل", description: "إدارة وتنمية التفاعل مع الجمهور." },
        "Professional Content Publishing": { title: "نشر محتوى احترافي", description: "نشر محتوى احترافي عبر القنوات المختلفة." },
        "Performance Tracking": { title: "متابعة الأداء", description: "مراقبة وتقارير الأداء الرقمي." },
        "Ads Management": { title: "إدارة الحملات الإعلانية", description: "إدارة الحملات الإعلانية الرقمية." },
        "SEO Optimization": { title: "تحسين محركات البحث", description: "تحسين ظهور المواقع في محركات البحث." },
        "Email Marketing": { title: "التسويق عبر البريد", description: "حملات بريد إلكتروني استراتيجية." },
        "Content Marketing": { title: "تسويق المحتوى", description: "إنشاء وتوزيع محتوى تسويقي." },
        "Market Study": { title: "دراسة السوق", description: "أبحاث ودراسات سوق شاملة." },
        "Competitor Analysis Mkt": { title: "تحليل المنافسين", description: "تحليل معمق للمنافسين." },
        "Target Audience Definition": { title: "تحديد الجمهور المستهدف", description: "تحديد وتحليل شرائح الجمهور المستهدف." },
        "Brand Building": { title: "بناء العلامة التجارية", description: "تطوير استراتيجي لحضور العلامة التجارية." },
        "Promotional Campaigns": { title: "حملات ميدانية", description: "حملات ترويجية ميدانية." },
        "Print Distribution": { title: "توزيع منشورات", description: "توزيع المواد الترويجية المطبوعة." },
        "Events Organization": { title: "تنظيم فعاليات", description: "تخطيط وتنظيم كامل للفعاليات." },
        "Promoters": { title: "المروجون", description: "توظيف وإدارة المروجين الميدانيين." },
        "Flyers": { title: "منشورات دعائية", description: "طباعة منشورات دعائية عالية الجودة." },
        "Brochures": { title: "مطويات", description: "طباعة مطويات مخصصة." },
        "Posters": { title: "ملصقات", description: "طباعة ملصقات كبيرة الحجم." },
        "Roll-ups": { title: "لافتات رول أب", description: "لافتات رول أب احترافية." },
        "Business Cards": { title: "بطاقات عمل", description: "طباعة بطاقات عمل فاخرة." },
        "Administrative Files": { title: "ملفات إدارية", description: "ملفات إدارية مطبوعة ومخصصة." },
        "Official Envelopes": { title: "أظرفة رسمية", description: "أظرفة تحمل هوية المؤسسة." },
        "Notebooks": { title: "دفاتر", description: "دفاتر مخصصة تحمل هوية العلامة." },
        "Visual Identity Design": { title: "تصميم هوية بصرية", description: "حزمة كاملة لتصميم الهوية البصرية." },
        "Printing Execution": { title: "تنفيذ الطباعة", description: "إدارة شاملة لتنفيذ أعمال الطباعة." },
        "Fast Delivery": { title: "تسليم سريع", description: "خدمات تصميم وطباعة عاجلة." },
        "High Quality Output": { title: "جودة عالية", description: "مخرجات بجودة عالية لجميع الأعمال." },
        "Initial Legal Consultation": { title: "استشارة قانونية أولية", description: "استشارة أولية حول المسائل القانونية." },
        "Contract Review": { title: "مراجعة العقود", description: "مراجعة مهنية للعقود." },
        "Regulatory Advice": { title: "نصائح تنظيمية", description: "نصائح تنظيمية وامتثالية للمؤسسات." },
        "Administrative Legal Support": { title: "دعم في الإجراءات", description: "دعم في الوثائق والإجراءات القانونية الإدارية." }
    }
};

export default serviceCopy;
